# ===================================================
#  VISCOUS GUBSER FLOW WITH CONSERVED CHARGES (VGCC)
# ===================================================
# DESCRIPTION: This configuration file contains the
# parameters needed for the viscous Gubser solution
# with conserved charges.
# ===================================================

# ===================================================
#           CONFIGURATION PARAMETERS
# ===================================================
# -----------------------------
# Time Evolution Parameters
# -----------------------------
tau_0: 1.0        # Initial proper time (fm/c)
tau_f: 2.0        # Final proper time (fm/c)
tau_step: 0.10    # Time step (fm/c)

# -----------------------------
# Spatial Grid Parameters
# -----------------------------
x_min: -5.0       # Minimum x coordinate (fm)
x_max: 5.0        # Maximum x coordinate (fm)
x_step: 0.050      # Step size in x (fm)
y_min: -5.0       # Minimum y coordinate (fm)
y_max: 5.0        # Maximum y coordinate (fm)
y_step: 0.050      # Step size in y (fm)

# -----------------------------
# Initial Conditions (in Gubser coordinates)
# -----------------------------
T_hat_0: 1.2    # Initial temperature
pi_hat_0: 0.0     # Initial reduced shear stress component
muB_hat_0: 0.36  # Initial baryon chemical potential
muS_hat_0: 0.000  # Initial strangeness chemical potential
muQ_hat_0: 0.000  # Initial electric charge chemical potential

# -----------------------------
# Equation of State (EoS) Parameters
# -----------------------------
T_ast: 1.000      # Temperature scale (GeV)
muB_ast: 1.000    # Baryon chemical potential scale (GeV)
muS_ast: 1.000    # Strangeness chemical potential scale (GeV)
muQ_ast: 1.000    # Electric charge chemical potential scale (GeV)

# -----------------------------
# Other Parameters
# -----------------------------
eta_over_s: 0.20  # Shear viscosity over entropy density
C: 5.0            # Relaxation time constant
q: 1.0            # Gubser dimensionful parameter (fm^-1)

# -----------------------------
# Output Configuration
# -----------------------------
output_dir: "data/output/analytic_solutions/EoS2/mu_over_T_0.3/"